//
// Created by Guillaume Tran on 28/04/2024.
//

#ifndef B_OOP_400_MPL_4_1_RAYTRACER_ROBIN_GLAUDE_MAIN_HPP
#define B_OOP_400_MPL_4_1_RAYTRACER_ROBIN_GLAUDE_MAIN_HPP


class main {

};


#endif //B_OOP_400_MPL_4_1_RAYTRACER_ROBIN_GLAUDE_MAIN_HPP
