name: Coding Style Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Temporary Directory
      run: mkdir temp

    - name: Pull Docker Container
      run: docker pull ghcr.io/epitech/coding-style-checker:latest

    - name: Run Coding Style Checker
      run: docker run --name coding-style-checker --volume $PWD:/project --volume $PWD/temp:/temp ghcr.io/epitech/coding-style-checker:latest /project /temp

    - name: Change Ownership of Reports
      run: sudo chown runner:runner temp/coding-style-reports.log

    - name: Display Reports
      run: cat temp/coding-style-reports.log

    - name: Validate Rule
      run: |
        if [ -s temp/coding-style-reports.log ]; then
          echo "Coding style check failed. Please fix the errors."
          cat temp/coding-style-reports.log
          exit 1
        else
          echo "Coding style check passed."
        fi
