name: Make Re

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libconfig++-dev
        sudo apt-get install -y libsfml-dev
        sudo apt-get install -y libsfml-dev

    - name: Run make re
      run: |
        mkdir build
        cd build
        cmake .. && cmake --build .
        if [ $? -eq 0 ]; then
          echo "make re succeeded."
        else
          echo "make re failed. Please fix the errors and try again."
          exit 1
        fi
